repo_url: https://github.com/GUGOFO/Xadrez
repo_name: Xadrez

site_url: https://github.com/GUGOFO/Xadrez/
site_name: Xadrez React
site_description: Reproduzindo o jogo Xadrez
site_author: GUGOFO

nav:
  - Home: index.md
  
  - Requisitos: 
    - Declaraçâo dos Requisitos: requisitos/requisitos.md
    - MoSCoW: requisitos/moscow.md
    - Matriz de Valor vs. Esforço: requisitos/valorEsforco.md
    - Produto Mínimo Viável: requisitos/mvp.md

  - BackLog:
    - BackLog Geral: backlog/backlog.md
    - User Storys:
      - US01: backlog/US/US01.md
      - US02: backlog/US/US02.md
      - US03: backlog/US/US03.md
      - US04: backlog/US/US04.md
      - US05: backlog/US/US05.md
      - US06: backlog/US/US06.md
      - US07: backlog/US/US07.md
      - US08: backlog/US/US08.md
      - US09: backlog/US/US09.md
      - US10: backlog/US/US10.md
      - US11: backlog/US/US11.md
      - US12: backlog/US/US12.md
      - US13: backlog/US/US13.md

  - Desenvolvedor: Desenvolvedor/desenvolvedor.md

theme:
  name: material
  logo: img/Logo.png
  favicon: img/Logo.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Modo Noturno
    - scheme: slate
      primary: purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Modo Claro


markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - attr_list